nodes:
- input.visual:
    source: 0
- model.yolo:
    detect: ["person"]
- dabble.bbox_count
- dabble.statistics:
    identity: count
- draw.bbox
- draw.legend:
    show: ["count"]
- output.screen
- custom_nodes.output.sqlite